update submodules

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,10 +74,9 @@ jobs:
           HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
         run: |
           brew install \
-            autoconf automake libtool autoconf-archive gobject-introspection \
+            autoconf automake libtool autoconf-archive \
             byacc vala \
-            ninja || true # ignore brew link python error
-          pip install packaging meson==1.3.1 # 1.3.2 can't find python
+            ninja meson || true # ignore brew link python error
 
       - name: Build all
         run: ./skk.sh ${{ matrix.arch }}
