split skk to a separate job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,27 +22,20 @@ jobs:
         with:
           submodules: recursive
 
-      - uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
-
       - name: Install dependencies
         env:
           HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
         run: |
           brew install \
             extra-cmake-modules \
-            autoconf automake libtool autoconf-archive gobject-introspection \
-            byacc vala \
             ninja || true # ignore brew link python error
-          pip install packaging meson==1.3.1 # 1.3.2 can't find python
 
       - name: Download and extract Fcitx5.app
         run: |
           wget https://github.com/fcitx-contrib/fcitx5-macos/releases/download/latest/Fcitx5-${{ matrix.arch }}.tar.bz2
           sudo tar xjvf Fcitx5-${{ matrix.arch }}.tar.bz2 -C "/Library/Input Methods"
 
-      - name: Build all
+      - name: Build non-skk
         run: ./all.sh ${{ matrix.arch }}
 
       - name: Upload artifact
@@ -56,8 +49,51 @@ jobs:
         if: ${{ failure() }}
         uses: mxschmitt/action-tmate@v3
 
+  build-skk:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [macos-14, macos-13]
+        include:
+          - { os: macos-14, arch: arm64 }
+          - { os: macos-13, arch: x86_64 }
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+
+      - name: Install dependencies
+        env:
+          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
+        run: |
+          brew install \
+            autoconf automake libtool autoconf-archive gobject-introspection \
+            byacc vala \
+            ninja || true # ignore brew link python error
+          pip install packaging meson==1.3.1 # 1.3.2 can't find python
+
+      - name: Build all
+        run: ./skk.sh ${{ matrix.arch }}
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: artifact-skk-${{ matrix.arch }}
+          path: |
+            build/*.tar.bz2
+
+      - name: Setup tmate session
+        if: ${{ failure() }}
+        uses: mxschmitt/action-tmate@v3
+
   release:
-    needs: build
+    needs: [build, build-skk]
     if: ${{ github.ref == 'refs/heads/master' }}
     runs-on: ubuntu-latest
     steps:
