update submodules (#43)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -65,19 +65,14 @@ jobs:
         with:
           submodules: recursive
 
-      - uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
-
       - name: Install dependencies
         env:
           HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
         run: |
           brew install \
-            autoconf automake libtool autoconf-archive gobject-introspection \
+            autoconf automake libtool autoconf-archive \
             byacc vala \
-            ninja || true # ignore brew link python error
-          pip install packaging meson==1.3.1 # 1.3.2 can't find python
+            ninja meson || true # ignore brew link python error
 
       - name: Build all
         run: ./skk.sh ${{ matrix.arch }}
