prepare for beta release (#23)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,19 +27,20 @@ jobs:
           python-version: '3.12'
 
       - name: Install dependencies
+        env:
+          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
         run: |
           brew install \
             extra-cmake-modules \
             autoconf automake libtool autoconf-archive gobject-introspection \
             byacc vala \
-            ninja
+            ninja || true # ignore brew link python error
           pip install packaging meson==1.3.1 # 1.3.2 can't find python
 
       - name: Download and extract Fcitx5.app
         run: |
-          wget https://github.com/fcitx-contrib/fcitx5-macos/releases/download/latest/Fcitx5-${{ matrix.arch }}.dmg
-          hdiutil attach Fcitx5-${{ matrix.arch }}.dmg
-          sudo cp -r /Volumes/Fcitx5/{Fcitx5.app,"Input Methods"}
+          wget https://github.com/fcitx-contrib/fcitx5-macos/releases/download/latest/Fcitx5-${{ matrix.arch }}.tar.bz2
+          sudo tar xjvf Fcitx5-${{ matrix.arch }}.tar.bz2 -C "/Library/Input Methods"
 
       - name: Build all
         run: ./all.sh ${{ matrix.arch }}
